apiVersion: v1
kind: ServiceAccount
metadata:
  name: connect-agent
  labels:
    app: connect

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: connect-agent
  labels:
    app: connect
rules:
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: connect-agent
  labels:
    app: connect
subjects:
- kind: ServiceAccount
  name: connect-agent
roleRef:
  kind: Role
  name: connect-agent
  apiGroup: rbac.authorization.k8s.io
